app:
  security:
    authorize:
      /user1/**: ADMIN,USER_1
      /user2/**: ADMIN,USER_2
      /**: ADMIN
    authenticate:
      user1: { name: user1, password: user1, role: USER_1 }
      user2: { name: user2, password: user2, role: USER_2 }
      admin: { name: admin, password: admin, role: ADMIN }
security.basic.enabled: false
spring.mvc.locale: fi_FI
